module.exports = {
    "How to accesses LLN ?": "how-come-to-belgium",
    "How to goes in Belgium": "how-come-to-belgium",
    "When are the exam start ?": "when-exams",
    "What if I has hungry?": "are-there-student-restaurants",
    "where can I eats ?": "are-there-student-restaurants",
    "How is appening the evaluations ?": "what-grading-syst",
    "are cellphones allow during the exam ?": "can-I-have-phone-exam",
    "Who can I contacts to register": "contact-enrolment-office",
    "Can I have a list of the course ?": "where-course-descriptions",
    "Is it possible to take french courses?": "can-french-course",
    "How can I contact my faculties ?": "contact-faculty",
    "Where can I find the contacts information of my faculty": "contact-faculty",
    "I heard talking about KAP, what are they ?": "what-is-kap",
    "Will I get a uclouvain email addresses ?": "do-i-get-email-address",
    "What is the price of train tickets ?": "train-ticket-cost",
    "Is it expensive to take trains ?": "train-ticket-cost",
    "schedule trains ?": "where-get-schedule",
    "Are there a lot of train ?": "where-get-schedule",
    "Is is possible to have student reductions for the train tickets ?": "train-ticket-cost",
    "What can I find as accommodation ?": "what-kot-types",
    "what type of accommodations": "what-kot-types",
    "what types of kot are there?": "what-kot-types",
    "Where can I find accommodations ?": "where-kots",
    "can I get more info about UCLouvain shared kot?": "more-info-ucl-shared-kot",
    "Can I have more information about UCL kot": "more-info-ucl-shared-kot",
    "Do you know hotels nearby ?": "are-there-hotels",
    "Is there hotel ?": "are-there-hotels",
    "Is there a IBIS hotels ?": "are-there-hotels",
    "What is the price of babysitting service": "cost-childcare",
    "What is the road laws ?": "driving-rules",
    "Is there particular driving rule ?": "driving-rules",
    "What is the easiest ways to go around LLN ?": "get-around-lln",
    "Is there a wifi for students ?": "is-there-wifi-ucl",
    "How to connects on eduroam wifi ?": "how-connect-eduroam",
    "Where can I find a map for the auditoria ?": "where-auditorium",
    "Where are given the class ?": "where-auditorium",
    "How many times can I pass an exams ?": "how-many-times-exams",
    "Is it true that we can pass two time an exam ?": "how-many-times-exams",
    "What if I cheat at an exams ?": "what-if-cheat",
    "What budgets should I plan ?": "how-much-budget",
    "How much cost a years in Belgium ?": "how-much-budget",
    "How register for the class ?": "how-register-courses",
    "How can I sign up for a classes ?": "how-register-courses",
    "Are the wastes sorted ?": "how-waste-management",
    "Is there specific trash bags for sorting ?": "how-waste-management",
    "Yes, that I already knew": "I-know",
    "Is there course where it are mandatory to go ?": "important-courses",
    "are there mandatory lecture": "important-courses",
    "Is there a post services ?": "is-there-post",
    "What mean ECTS ?": "what-is-ects",
    "What is the minimal amounts of ECTS I need to take ?": "min-max-workload",
    "what about maximal amount of works": "min-max-workload",
    "What is a kots ?": "kot-meaning",
    "Do I need to know French to follow class ?": "need-french",
    "Are the class in French ?": "need-french",
    "Are there class of French ?": "what-available-lang-courses",
    "Is it allowed to sublet ?": "may-sublet",
    "is it nice in Belgium": "is-belgium-nice",
    "How is Belgium ?": "is-belgium-nice",
    "I'm Belgian": "ans:give-nationality",
    "web sites ?": "what-ucl-website",
    "What is the UCLouvain web sites ?": "what-ucl-website",
    "Is there facility to use bikes in Belgium ?": "possible-to-bike",
    "Is it easy to bikes in LLN ?": "possible-to-bike",
    "What school are there at Uclouvain ?": "schools-in-lln",
    "Is UCLouvain a catholique schools ?": "religion-allowed-ucl",
    "Do i has to be christian in ucl?": "religion-allowed-ucl",
    "What are the religion allowed in Belgium ?": "religion-allowed-ucl",
    "What are the religion in Belgium ?": "what-religion-belgium",
    "is there religions forbitten in Belgium ?": "religion-allowed-belgium",
    "is it not permitted to profess my own religious belief in Belgium?": "religion-allowed-belgium",
    "What is the role of the student delegates ?": "student-delegate",
    "Can you give me typical prices of every day stuff ?": "typical-everyday-costs",
    "what cost every day lifes in Belgium ?": "typical-everyday-costs",
    "What in fact are customary cost in Belgium?": "typical-everyday-costs",
    "What are customary cost in Belgium?": "typical-everyday-costs",
    "where are located UCLouvain sites ?": "ucl-physical-sites",
    "what are the UCLouvain sites ?": "ucl-physical-sites",
    "what exactly are ucl site": "ucl-physical-sites",
    "Is there a Welcome brochures ?": "welcome-guide",
    "Is there a guides for foreign student ?": "welcome-guide",
    "handbooks for foreigner ?": "welcome-guide",
    "What is the tax applied on products ?": "vat-in-belgium",
    "Where is the access cards used ?": "what-access-card-for",
    "Can I have the academic calendars ?": "what-academic-calendar",
    "When start the years ?": "what-academic-calendar",
    "UCL": "what-is-ucl",
    "What mean UCL ?": "what-is-ucl",
    "What is the concepte of majors ?": "what-major",
    "What are my uclouvain ?": "what-myucl-for",
    "What is my uclouvain accounts ?": "what-myucl-for",
    "Is there option to choose ?": "what-options",
    "What are the option ?": "what-options",
    "Is there specialisation ?": "what-options",
    "where are Moodle ?": "what-moodle",
    "information on moodle ?": "what-moodle",
    "How is you called ?": "who-are-you",
    "Have you a name ?": "who-are-you",
    "Is JAQ your Name ?": "who-are-you",
    "What about the secondary educations ?": "what-school-system",
    "How is organized the childrens education ?": "what-school-system",
    "what does the school systems look like ?": "what-school-system",
    "what is the passwords of ade ?": "what-password-ade",
    "How can I have the codes for ade ?": "what-password-ade",
    "Codes for ade ?": "what-password-ade",
    "What are the identifier and password of ADE ?": "what-password-ade",
    "What is ADE": "what-service-schedule",
    "What webpage is used to build schedule at UCL": "what-service-schedule",
    "What is a mutuelles ?": "what-mutuelle",
    "How is called an health insurances in Belgium ?": "what-mutuelle",
    "What are the noma ?": "what-student-card-noma-for",
    "When should I uses my noma ?": "what-student-card-noma-for",
    "What is the usages of the NOMA ?": "what-student-card-noma-for",
    "When are the Esplanade open ?": "when-city-hall-open",
    "When is the the shoppings center opening ?": "when-city-hall-open",
    "How are given the grade ?": "what-var-evaluation",
    "On what criteria are given the point ?": "what-var-evaluation",
    "How are assessment graded?": "what-var-evaluation",

    // out of context example:
    "where can I find some beers?": "Default Fallback Intent",
    "How can I go to Paris ?": "Default Fallback Intent",
    "Can I have a pets in the accomodation ?": "Default Fallback Intent",
}