module.exports = {
    "How to access LN ?": "how-come-to-belgium",
    "How to go in Belgia": "how-come-to-belgium",
    "When are the exams start ?": "when-exams",
    "What if I have angry?": "are-there-student-restaurants",
    "where can I eet ?": "are-there-student-restaurants",
    "How is apening the evaluation ?": "what-grading-syst",
    "are celphone allow during the exam ?": "can-I-have-phone-exam",
    "Who can I contact to regester": "contact-enrolment-office",
    "Can I have a list of the coorses ?": "where-course-descriptions",
    "Is it possible to take french cuorse?": "can-french-course",
    "How can I contact my faculti ?": "contact-faculty",
    "Where can I fond the contact information of my faculty": "contact-faculty",
    "I heard tolking about KAP, what is it ?": "what-is-kap",
    "Will I get a uclouvain imail address ?": "do-i-get-email-address",
    "What is the proce of a train ticket ?": "train-ticket-cost",
    "Is it expensive to take th train ?": "train-ticket-cost",
    "shedule train ?": "where-get-schedule",
    "Is there a lotof train ?": "where-get-schedule",
    "Is is possible to have stduent reduction for the train tickets ?": "train-ticket-cost",
    "What can I find as accommodations ?": "what-kot-types",
    "what type of accomodation": "what-kot-types",
    "what types of kots are their?": "what-kot-types",
    "Where can I find acommodation ?": "where-kots",
    "can I get plus info about UCLouvain shared kots?": "more-info-ucl-shared-kot",
    "Can I have more information about UCL cots": "more-info-ucl-shared-kot",
    "Do you know a hotel neerby ?": "are-there-hotels",
    "Is their hotels ?": "are-there-hotels",
    "Is ther a IBIS hotel ?": "are-there-hotels",
    "What is the price price of babysitting services": "cost-childcare",
    "What is the rood law ?": "driving-rules",
    "Is there particular driving rulles ?": "driving-rules",
    "What is the easiest wai to go around LLN ?": "get-around-lln",
    "Is there a wiif for student ?": "is-there-wifi-ucl",
    "How to conect on eduroam wifi ?": "how-connect-eduroam",
    "Where can I find a map for the auditoirum ?": "where-auditorium",
    "Where are gaven the classes ?": "where-auditorium",
    "How many times can I passs an exam ?": "how-many-times-exams",
    "Is it tru that we can pass two times an exam ?": "how-many-times-exams",
    "What if I cheet at an exam ?": "what-if-cheat",
    "What budget shoudl I plan ?": "how-much-budget",
    "How much cots a year in Belgium ?": "how-much-budget",
    "How register for the clasess ?": "how-register-courses",
    "How can I sign up for an class ?": "how-register-courses",
    "Are the wast sorted ?": "how-waste-management",
    "Is there spacific trash bag for sorting ?": "how-waste-management",
    "Yes, that I already new": "I-know",
    "Is there course were it is mandatory to go ?": "important-courses",
    "are there mandatorry lectures": "important-courses",
    "Is there a post serice ?": "is-there-post",
    "What mens ECTS ?": "what-is-ects",
    "What is the minimal amount of ECTS I nrrd to take ?": "min-max-workload",
    "what about maximal amount of work": "min-max-workload",
    "What si a kot ?": "kot-meaning",
    "Do I need to know French to fallow classes ?": "need-french",
    "Are the klasses in French ?": "need-french",
    "Are there classes of French ?": "what-available-lang-courses",
    "Is it allowed ot sublet ?": "may-sublet",
    "is it nice ni Belgium": "is-belgium-nice",
    "How is Belgique ?": "is-belgium-nice",
    "I ma Belgian": "ans:give-nationality",
    "web site ?": "what-ucl-website",
    "What is the UCLouvain website ?": "what-ucl-website",
    "Is there faciliti to use bike in Belgium ?": "possible-to-bike",
    "Is it isy to bike in LLN ?": "possible-to-bike",
    "What shool is there at Uclouvain ?": "schools-in-lln",
    "Is UCLouvain a catolique school ?": "religion-allowed-ucl",
    "Do i hav to be christian in ucl?": "religion-allowed-ucl",
    "What are the religions alowed in Belgium ?": "religion-allowed-ucl",
    "What are the religions in Beligum ?": "what-religion-belgium",
    "is there religion forbitten into Belgium ?": "religion-allowed-belgium",
    "is it not permitted to profess my own religious believ in Belgium?": "religion-allowed-belgium",
    "What is the rol of the student delegate ?": "student-delegate",
    "Can you give me typical price of every day stuf ?": "typical-everyday-costs",
    "what cost every day live in Belgium ?": "typical-everyday-costs",
    "What in fact are custom costs in Belgium?": "typical-everyday-costs",
    "What are custommary costs in Belgium?": "typical-everyday-costs",
    "wher are located UCLouvain site ?": "ucl-physical-sites",
    "wat are the UCLouvain site ?": "ucl-physical-sites",
    "what exactlly are ucl sites": "ucl-physical-sites",
    "Is there a Welkome brochure ?": "welcome-guide",
    "Is there a guide for foreygn student ?": "welcome-guide",
    "handbook of foreigner ?": "welcome-guide",
    "What is the taxation applied on product ?": "vat-in-belgium",
    "Where is the access card usef ?": "what-access-card-for",
    "Can I have the academic calender ?": "what-academic-calendar",
    "When start the yeer ?": "what-academic-calendar",
    "UCL": "what-is-ucl",
    "What meens UCL ?": "what-is-ucl",
    "What is the concept of major ?": "what-major",
    "What us my uclouvain ?": "what-myucl-for",
    "What id my uclouvain account ?": "what-myucl-for",
    "Is there options to chose ?": "what-options",
    "What arethe options ?": "what-options",
    "Is there specialisacion ?": "what-options",
    "wehre is Moodle ?": "what-moodle",
    "informasion on moodle ?": "what-moodle",
    "How are you cold ?": "who-are-you",
    "Have youa name ?": "who-are-you",
    "Is JAQ yor Name ?": "who-are-you",
    "What about the secondari education ?": "what-school-system",
    "How is organized the shildren education ?": "what-school-system",
    "what dos the school system look like ?": "what-school-system",
    "what is the pasword of ade ?": "what-password-ade",
    "How can I have the code forr ade ?": "what-password-ade",
    "Codde for ade ?": "what-password-ade",
    "What is the identifier and pasword of ADE ?": "what-password-ade",
    "hat is ADE": "what-service-schedule",
    "What webpage is used to build shedules at UCL": "what-service-schedule",
    "Wha is a mutuelle ?": "what-mutuelle",
    "How is cold an health insurance in Belgium ?": "what-mutuelle",
    "What is thr noma ?": "what-student-card-noma-for",
    "When should I uss my noma ?": "what-student-card-noma-for",
    "What is the usagge of the NOMA ?": "what-student-card-noma-for",
    "When is the Esplanade oppen ?": "when-city-hall-open",
    "When is the the schopping center opening ?": "when-city-hall-open",
    "Howare given the grades ?": "what-var-evaluation",
    "On what criteria are gaven the points ?": "what-var-evaluation",
    "How are asessments graded?": "what-var-evaluation",

    // out of context example:
    "where can I find some ber?": "Default Fallback Intent",
    "Ho can I go to Paris ?": "Default Fallback Intent",
    "Can I have a pet in the accomodation ?": "Default Fallback Intent",
}